version: '3.7'

services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always


