# base image
FROM python:3.6.5-alpine

# set working directory
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install dependencies
RUN \
 python3 -m pip install --upgrade pip && \
 python3 -m pip install -r requirements.txt
# add app
COPY . /usr/src/app
ENV FLASK_APP=project/__init__.py
# run server
CMD ["python","-m", "flask", "run", "-h", "0.0.0.0"]