version: '3.7'
services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - './:/usr/src/app'
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
